### PR TITLE
`/subscriptions/v2` > `/subscription-seats`

### PR DESCRIPTION
**Pull request by chenhunghan**

### CODE REVIEW

**Comment by DmitriyNoa** [comment]
Maybe it's better to add a separate method? At least for the migration period. WDYT?

**Comment by chenhunghan** [comment]
> Maybe it's better to add a separate method? At least for the migration period. WDYT?

Are we using v2 endpoint in production already?

**Comment by DmitriyNoa** [comment]
> > Maybe it's better to add a separate method? At least for the migration period. WDYT?
> 
> Are we using v2 endpoint in production already?

No, we don't. I just thought that having 2 methods could allow for easier rollbacks if something happens....

**Comment by nevalla** [comment]
I think this is fine...`v2` should not be in use anymore or if we are using we should change it.

**Review by nevalla — APPROVED** [review]

**Pull request merged**
